trigger:
- main

pool: Default

variables:
- name: NODE_ENV
  value: development

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd servers/express/api-with-express-and-handlebars
    npm install
    npm run test
  displayName: 'npm install and test'

- task: Docker@2
  inputs:
    containerRegistry: 'sycured on docker hub'
    repository: 'sycured/tsco-ado-node'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
